### ISSUE TITLE
Deliver Clojure Client for v1.0 Mesos HTTP APIs

### ISSUE THREAD

**Issue by oubiwann** [clojusc/meson#2]
Milestone 0.1.0
- [x] Setup testing infrastructure - ticket #40
- [x] Add project documentation - ticket #65 
- [x] Reorganize existing protobufs into modular namespaces - ticket #29 
- [x] Add HTTP verb wrappers- ticket  #24
- [x] Update namespaces for Meson Client, Scheduler, and Executor APIs - ticket #49 
- [x] Support API event streams - ticket #56
- [x] Implement v1.0 Scheduler API - ticket #4 

Milestone 0.2.0
- [ ] Implement Agent API - ticket #59
- [ ] Implement v1.0 Executor API - ticket #5 

Milestone 0.3.0
- [ ] Implement Master API - ticket #58
- [ ] Implement v1.0 Operator API - ticket #6 

Milestone 1.0.0
- [ ] Add Meson Examples - ticket #73

**Comment by wdhowe** [comment]
Under Milestone 0.1.0, it appears that the following associated issues can be marked complete:

- Add HTTP verb wrappers- ticket #24
- Update namespaces for Meson Client, Scheduler, and Executor APIs - ticket #49
