### ISSUE TITLE
Add v1.0 Scheduler API

### ISSUE THREAD

**Issue by oubiwann** [clojusc/meson#4]
Official docs are here:  http://mesos.apache.org/documentation/latest/scheduler-http-api/

Tasks:
- [ ] Implement Scheduler API JSON types - #28
- [ ] Implement Scheduler Calls - #7
- [x] Provide Default Handler for Scheduler Events - #8

Part of epic #2

**Comment by wdhowe** [comment]
This is now complete: Implement Scheduler Calls - #7

**Comment by oubiwann** [comment]
NICE.
