### ISSUE TITLE
Setup testing infrastructure

### ISSUE THREAD

**Issue by billota** [clojusc/meson#40]
Feature tasks:
- [x] Add testing profile - #34
- [x] Fix failing tests - #27 
- [x] Fix lint errors - #41
- [x] Setup Travis CI Docker to install and run Mesos - #37
- [x] Utilize TravisCI Mesos dockerfile for local testing - #38
- [x] Create example unit, integration, and system tests - #39

Part of epic #2

**Comment by hromagnum** [comment]
Done!
