### ISSUE TITLE
Ditch protobufs for serialization; use JSON instead

### ISSUE THREAD

**Issue by oubiwann** [clojusc/meson#50]
We're going to support only JSON for this library. However, we will provide the ability of using protobufs (and converting those to JSON) for those who want to using existing types from Mesomatic.

Tasks:
- [ ] Move Mesomatic protobuf type conversion functions into `meson.mesomatic` - #60
- [ ] Change `protobuf` namespace to `json` - #61
- [ ] Convert existing protobuf-centric records to json-centric records - #62
- [x] Remove unnecessary protobuf code - #63

Part of epic #2

**Comment by oubiwann** [comment]
Yeah, we're going to do this. I'll update the description with task tickets.
