### ISSUE TITLE
Support API event streams

### ISSUE THREAD

**Issue by oubiwann** [clojusc/meson#56]
The Mesos HTTP API requires support for long-lived connections to the scheduler and executor in order to stream events for each of these. In addition, the new operator API also publishes events via long-lived HTTP connections.

Tasks:
- [x] Devise an appropriate means for reading stream data from a long-lived HTTP connection - #51
- [x] Create a namespace and functions for parsing streamed data - #52
- [x] Define a best-practice and mechanism for event handlers - #53
- [x] Create integration tests for streaming connections  - #54

Wont do:
- Create integration tests for  event handling - #55 

The reason that #55 won't be done as part of this feature is that the code for the event handling will actually be landing in different tickets for each individual HTTP API event handler.

Part of epic #2

**Comment by oubiwann** [comment]
Done.
