### ISSUE TITLE
Add v1.0 Operator API

### ISSUE THREAD

**Issue by oubiwann** [clojusc/meson#6]
Official docs are here:  http://mesos.apache.org/documentation/latest/operator-http-api/

Tasks:
- [ ] Implement Operator API protobuf types - ticket #33
- [ ] Implement Operator Calls - ticket #12 
- [ ] Provide Default Handler for Operator Events - ticket #13  

Part of epic #2

**Comment by wdhowe** [comment]
This Task can be marked as complete: Implement Operator API protobuf types - ticket #33
