### ISSUE TITLE
Add High-Availability Support

### ISSUE THREAD

**Issue by oubiwann** [clojusc/meson#70]
Tasks:
- [ ] Add Reconnection Support for all Subscribers - #67
- [ ] Update Scheduler API  to use new Reconnection Support - #69
- [ ] Update Executor API to use new Reconnection Support - #71
- [ ] Update Operator API to use new Reconnection Support - #72
- [ ] Add Master Redirection Support - #68

Part of epic #2
